package org.enhydra.jawe.shark;



/**
 * @author Sasa Bojanic
 *
 */
public final class SharkValidationErrorIds {

   public static final String ERROR_SCRIPT_NOT_DEFINED="ERROR_SCRIPT_NOT_DEFINED";
   public static final String ERROR_UNSUPPORTED_SCRIPT="ERROR_UNSUPPORTED_SCRIPT";
   public static final String ERROR_UNSUPPORTED_DATA_TYPE="ERROR_UNSUPPORTED_DATA_TYPE";
  
   public static final String ERROR_MANUAL_START_MODE_FOR_TOOL_ACTIVITY_WITH_SYSTEM_PARTICIPANT_PERFORMER="ERROR_MANUAL_START_MODE_FOR_TOOL_ACTIVITY_WITH_SYSTEM_PARTICIPANT_PERFORMER";   
   public static final String ERROR_SYSTEM_PARTICIPANT_PERFORMER_FOR_NO_IMPLEMENTATION_ACTIVITY="ERROR_SYSTEM_PARTICIPANT_PERFORMER_FOR_NO_IMPLEMENTATION_ACTIVITY";   

   public static final String WARNING_TOOL_AGENT_CLASS_NOT_DEFINED="WARNING_TOOL_AGENT_CLASS_NOT_DEFINED";   

}